---
- name: Inclure les tâches spécifiques à Ubuntu/Debian
  include_tasks: ubuntu.yml
  when: ansible_os_family == "Debian"

- name: Inclure les tâches spécifiques à Rocky/RedHat
  include_tasks: rocky.yml
  when: ansible_os_family == "RedHat"

- name: Cloner le dépôt de l'application
  git:
    repo: "{{ app_repo }}"
    dest: "{{ app_dest }}"
    version: HEAD

- name: Installer les dépendances npm
  command: npm install
  args:
    chdir: "{{ app_dest }}"

- name: Compiler l'application (build)
  command: npm run build
  args:
    chdir: "{{ app_dest }}"

- name: Installer le serveur statique "serve"
  command: npm install -g serve

- name: Lancer l'application avec "serve"
  shell: nohup serve -s dist -l {{ app_port }} > /var/log/quiz-ansible.log 2>&1 &
  args:
    chdir: "{{ app_dest }}"
